export { default as FirestoreOverRest } from "./FirestoreOverRest"
export { default as QuickFirestore } from "./QuickFirestore"
export { default as QuickQuery } from "./QuickQuery"
export { default as typedValues } from "./FirestoreOverRest/typedValues"
export { buildTestFsDocument as buildTestFsDocument } from "./FirestoreOverRest/testTools"
export { FSDocument as FSDocument } from "./FirestoreOverRest/testTools"
